stages:
  - build
  - deploy

variables:
  BUILD_IMAGE:  docker:20.10.17-dind
  APPLICATION_NAME: "litecoin"

docker_build:
  stage: build
  image: $BUILD_IMAGE
  cache: {}
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --build-arg APPLICATION_NAME=$APPLICATION_NAME -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

.int_variables: &int_variables
  ENV: int
  KUBE_NAMESPACE: int
  REPO_URL: $REPO_URL_NP
  KUBE_CONTEXT: nonprod
  SKIP_DEPLOY: 1

.kubernetes_deploy_script: &kubernetes_deploy_script
  cache: {}
  before_script:
    - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
  script:
    - kubectl version
    - timeout 300 deployment/deploy.sh
    - rm -f $KUBECONFIG
  after_script:
    - vault token revoke -self

kube-deploy:
  stage: deploy
  cache: { }
  dependencies: [ ]
  image: bitnami/kubectl:1.21.14
  <<: *kubernetes_deploy_script
  variables:
    <<: *int_variables
