apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeName: pv01